### PR TITLE
Add QueryVendor

### PR DESCRIPTION
**Pull request by yeahdongcn**
Signed-off-by: Xiaodong Ye <yeahdongcn@gmail.com>

### CODE REVIEW

**Comment by powersj** [comment]
Hi!

Thanks for the PR. I will gladly take this!

Can you fix the two CI failures and then this is good to go:

```
$ make lint
golangci-lint run
cli.go:71:2: ifElseChain: rewrite if-else to switch statement (gocritic)
	if length == numSubDeviceIDs {
	^
cli.go:70:2: variable 'length' is only used in the if-statement (cli.go:71:2); consider using short syntax (ifshort)
	length := len(args)
	^
Makefile:24: recipe for target 'lint' failed
make: *** [lint] Error 1

The command "make lint" exited with 2.
```

**Comment by yeahdongcn** [comment]
Done.

One quick question: how to import `v2.0.0`?

**Review by powersj — APPROVED** [review]

**Comment by powersj** [comment]
@yeahdongcn thanks again! I just tagged v2.1.0 with your PR which you can use in your go.mod:

```
github.com/powersj/pciids v2.1.0
```

**Comment by yeahdongcn** [comment]
Thanks for the quick response!

I encountered this issue in `go mod tidy`: 
```
go.mod:8:2: require github.com/powersj/pciids: version "v2.1.0" invalid: should be v0 or v1, not v2
```

**Comment by yeahdongcn** [comment]
I guess the reason is functions like `QueryDevice` are under `main` package.

**Comment by powersj** [comment]
Ah sorry! I forgot to add `v2` to the go.mod. I fixed that and released v2.2.0:

```s
$ go get github.com/powersj/pciids/v2@v2.2.0
go: downloading github.com/powersj/pciids/v2 v2.2.0
go: added github.com/inconshreveable/mousetrap v1.0.0
go: upgraded github.com/pkg/errors v0.8.1 => v0.9.1
go: added github.com/powersj/pciids/v2 v2.2.0
go: upgraded github.com/sirupsen/logrus v1.2.0 => v1.8.1
go: added github.com/spf13/cobra v1.2.1
go: added github.com/spf13/pflag v1.0.5
go: upgraded golang.org/x/crypto v0.0.0-20190605123033-f99c8df09eb5 => v0.0.0-20200622213623-75b288015ac9
go: upgraded golang.org/x/sys v0.0.0-20190624142023-c5567b49c5d0 => v0.0.0-20211117180635-dee7805ff2e1
❯ go install github.com/powersj/pciids/v2@v2.2.0
❯ pciids --version
pciids version v2.2.0
❯ pciids 1ed5
1ed5:0100 - Moore Threads Technology Co.,Ltd MTT S10
1ed5:0101 - Moore Threads Technology Co.,Ltd MTT S10
1ed5:0102 - Moore Threads Technology Co.,Ltd MTT S30
1ed5:0105 - Moore Threads Technology Co.,Ltd MTT S50
1ed5:0106 - Moore Threads Technology Co.,Ltd MTT S60
1ed5:0111 - Moore Threads Technology Co.,Ltd MTT S100
1ed5:0121 - Moore Threads Technology Co.,Ltd MTT S1000M
1ed5:0122 - Moore Threads Technology Co.,Ltd MTT S1000
1ed5:0123 - Moore Threads Technology Co.,Ltd MTT S2000
1ed5:01ff - Moore Threads Technology Co.,Ltd MTT HDMI/DP Audio
1ed5:0201 - Moore Threads Technology Co.,Ltd G2D30
1ed5:0202 - Moore Threads Technology Co.,Ltd G2D20
1ed5:0203 - Moore Threads Technology Co.,Ltd G2D10
1ed5:0211 - Moore Threads Technology Co.,Ltd G2D40
1ed5:0221 - Moore Threads Technology Co.,Ltd G2S80
1ed5:0222 - Moore Threads Technology Co.,Ltd G2S85
1ed5:0223 - Moore Threads Technology Co.,Ltd G2S4
1ed5:0251 - Moore Threads Technology Co.,Ltd G2N10
1ed5:02ff - Moore Threads Technology Co.,Ltd MTT HDMI/DP Audio
```

**Comment by yeahdongcn** [comment]
I was trying to import this package, but as I said earlier https://github.com/powersj/pciids/pull/1#issuecomment-1258909954, I can no longer use `QueryDevice` in my program.

```
/main.go:9:2: import "github.com/powersj/pciids/v2" is a program, not an importable package
```

**Comment by powersj** [comment]
> I was trying to import this package, but as I said earlier [#1 (comment)](https://github.com/powersj/pciids/pull/1#issuecomment-1258909954), I can no longer use `QueryDevice` in my program.

Ah, I assumed incorrectly you were calling the CLI program. You are right with v2 I made it non-importable, but I have fixed that and released v2.3.0. Let me know if that works for you, and sorry for the confusion!

**Comment by yeahdongcn** [comment]
It now works awesome. Thank you!

**Pull request merged**
